apiVersion: v1
kind: Service
metadata:
  name: weaviate-grpc
  namespace: weaviate
  annotations: {}
spec:
  type: LoadBalancer
  loadBalancerSourceRanges: []
  selector:
    app: weaviate-cluster-3
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051

